services:
    discord-bot:
        build:
            context: .
            args:
                DATABASE_URL: ${DATABASE_URL}
        env_file: .env.docker
        volumes:
            - /app/node_modules
        depends_on:
            - db

    db:
        image: postgres:16
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '${DB_PORT}:${DB_PORT}'
volumes:
    db_data:
