services:
  discord-bot:
    build: 
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    env_file: .env.docker
    volumes: 
        - .:/app
    depends_on: 
        - db

  db:
    image: postgres:16
    env_file: .env.docker
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASS} 
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
volumes:
  db_data:
